sudo: false

language: node_js

dist: jammy

node_js:
  - "20.8.0"
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - corepack enable
  - yarn set version 3.6.4
  # https://bugs.launchpad.net/ubuntu/+source/docker-buildx/+bug/1968035/comments/23
  - wget http://ftp.ubuntu.com/ubuntu/pool/universe/d/docker-buildx/docker-buildx_0.11.2-0ubuntu2_amd64.deb
  - sudo dpkg -i docker-buildx_0.11.2-0ubuntu2_amd64.deb

install:
  - yarn --immutable
  - NODE_ENV=production npm run build

addons:
  chrome: stable

services:
  - docker

script:
  - npm test
  - ./artifact.sh

matrix:
  allow_failures:
    - node_js: "stable"
